name:  Auto Update RoarZone playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # প্রতি ১ ঘন্টা

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📥 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: 🔓 Decrypt ZIP files
        run: |
          python decrypt.py
        env:
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}

      - name: ▶️ Run RoarZone Generator
        run: |
          python main/RoarZone_sm.py

      - name: 💾 Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add RoarZone.m3u RoarZone_data.json
          git commit -m "🔄 Auto update RoarZone playlist" || echo "No changes"
          git push
